### ISSUE TITLE
[bug]: MixMonitor audio missing start of audio

### ISSUE THREAD

**Issue by wphowell** [asterisk/asterisk#455] opened 2023-11-22 00:50 UTC
### Severity

Trivial

### Versions

18.18.1

### Components/Modules

app_mixmonitor

### Operating Environment

FreePBX 16/CentOS 7

### Frequency of Occurrence

Occasional

### Issue Description

When the SAN is under high load, audio is missing the wav header and start of audio.  Stereo recordings also don't match up and can't be merged into a single 2-channel audio recording.

We were able to patch app_mixmonitor.c by adding fflush(mixmonitor->mixmonitor_ds->fs_write->f); after the loop that writes frames in mixmonitor_thread -- this appears to ensure that the writes get to the disk and no audio data is being lost.

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment] 2023-11-22 09:11
Do you plan on providing a pull request for including such a change?

**Comment by seanbright** [comment] 2023-11-22 11:29
Is Asterisk crashing? The buffers should be flushed implicitly when the `FILE *`s are closed so it’s not clear how an `fflush()` makes a difference if Asterisk isn’t crashing.

**Comment by wphowell** [comment] 2023-11-22 12:35
Asterisk does not crash.  I'm not sure of the nuance of the filesystem behaviour when the SAN disks are under high load.  We've seen that it seems to behave worse under XFS, but still see the issue on EXT4 as well.

Yes, I can submit a pull request with this change.

**Comment by seanbright** [comment] 2023-11-22 12:40
The patch will need to make this new behavior optional (a new application argument) that defaults to off.

Flushing should be happening when the files are closed so this seems like the wrong approach to me.

**Comment by seanbright** [comment] 2023-11-22 17:44
The more you describe this the less inclined I am to accept a PR that does an `fflush(...)` - optional or not. Can you provide instructions (config. dialplan, etc.) to reproduce this?

**Comment by wphowell** [comment] 2023-11-23 13:19
The underlying issue is a hot SAN as I've said earlier.  The start of the recording doesn't get stored on the disk most likely because the initial data being sent is buffered and lost before it get written to the disk -- it's only the initial data as we have not seen lost of audio anywhere else in the file.

It should be able to be reproduced if you can limit the IOPS on your storage device to a very low number and have at least two competing resources with about 100 simultaneous calls doing mono and stereo (3 recordings) -- we find that if we're only doing mono that the loss doesn't seem occur; it only loses the start of the receive and/or transmit recordings, and those cannot be merged because one side has loss the other side does not.

What is the reason for not at least allowing this is an option?  The patch seems to be working well for us.

**Comment by seanbright** [comment] 2023-11-23 13:35
> What is the reason for not at least allowing this is an option?

Because this…

> The start of the recording doesn't get stored on the disk most likely because the initial data being sent is buffered and lost before it get written to the disk

… does not make any sense to me. Why would only the initial part of the file have issues getting flushed? If you copy a large file to your SAN when it is heavily loaded is the initial part missing?

This needs further analysis and I’m not sure how we do that without being able to replicate your environment. This seems like a very niche issue. 

We used to restart Asterisk every night to reduce the chance of a crash. That worked well for us too, but it didn’t actually fix anything.

**Comment by seanbright** [comment] 2023-11-23 13:47
> Can you provide instructions (config. dialplan, etc.) to reproduce this?

> If you copy a large file to your SAN when it is heavily loaded is the initial part missing?

**Comment by jcolp** [comment] 2023-11-23 14:05
Something else to note is that fflush doesn't actually guarantee a flush to disk. It flushes the user-space buffers. So therefore: Is it possible for that buffer to not get flushed to kernel space normally (because of some filesystem issue or disk slowness) , and gets overwritten?

**Comment by jcolp** [comment] 2023-11-23 14:31
Additionally, until an analysis and explanation beyond "adding fflush solves this" is available and makes sense, then the change will not be merged. If other individuals are experiencing this issue and can provide additional information to narrow it down, then all the better as well.

**Comment by jcolp** [comment] 2023-12-21 19:09
Is any further investigation on this going to be done to understand why fflush resolves it in your environment?

**Comment by wphowell** [comment] 2023-12-21 19:57
We haven't come up with a good way to do that.  I'd suggest that we close this until we can come up with a way to get to the root of the issue.

**Closed** 2023-12-21 19:58 UTC
Labels: bug, wontfix, support-level-core
