### ISSUE TITLE
[bug]: Realtime postgresql_config.sql 

### ISSUE THREAD

**Issue by Michael-TX** [asterisk/asterisk#348] opened 2023-09-22 20:20 UTC
### Severity

Trivial

### Versions

20.4.0

### Components/Modules

contrib

### Operating Environment

OS Linux Debian 12

### Frequency of Occurrence

Constant

### Issue Description

Error occurred during SQL query execution

Reason:
SQL Error [42601]: ERROR: trailing junk after numeric literal at or near "100r"
  Position: 39

BUG
ALTER TABLE ps_endpoints ALTER COLUMN 100rel TYPE pjsip_100rel_values_v2 USING 100rel::text::pjsip_100rel_values_v2;

Line 1489 
100rel should be in quotes on both occurrence

ALTERED 
ALTER TABLE ps_endpoints ALTER COLUMN "100rel" TYPE pjsip_100rel_values_v2 USING "100rel"::text::pjsip_100rel_values_v2;

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment] 2023-09-22 20:55
This is a duplicate of #274 which has been fixed and is in 20.5.0-rc1.

**Closed by jcolp** 2023-09-22 20:55 UTC
Labels: bug, duplicate
