### ISSUE TITLE
[bug]: res_stir_shaken/verification.c: Getting verification errors when global_disable=yes

### ISSUE THREAD

**Issue by lukeescude** [asterisk/asterisk#879] opened 2024-09-11 15:08 UTC
### Severity

Trivial

### Versions

20.8.1

### Components/Modules

res_stir_shaken/verification.c

### Operating Environment

Debian 12 64-bit

### Frequency of Occurrence

Constant

### Issue Description

Since bumping to 20.8.1, we're seeing a lot of these:

ERROR[48859]: res_stir_shaken/verification.c:670 in ast_stir_shaken_vs_ctx_create: PJSIP/external-kamailio-000011ea: Must provide caller_id

Even though we have global_disable=yes in the [verification] object of stir_shaken.conf

This was not occurring on 20.7.0. We're not able to test past 20.8.1 until a vmodbc bug gets fixed (it's already merged, just not released yet). I am also not entirely sure how to reproduce it yet, as it's appearing in odd places in the log.

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by gtjoseph** [comment] 2024-09-11 15:23
Yep, we're not checking the global_disable flag until after we check callerid and profile.  We should be checking it first.

**Comment by gtjoseph** [comment] 2024-09-11 17:19
@lukeescude If you can test the pull request that'd be appreciated.

**Comment by lukeescude** [comment] 2024-09-11 18:25
Compiling now! Although I haven't had any success trying to recreate it in my dev environment yet, so my testing may not be practical.

**Comment by lukeescude** [comment] 2024-09-11 19:31
So far so good, I think you fixed it. Tested attestation too, just for the hell of it, and the headers are properly set in the outgoing INVITE.

**Comment by gtjoseph** [comment] 2024-09-11 19:33
Thanks @lukeescude!

**Comment by lukeescude** [comment] 2024-09-12 03:02
Well, crap - @gtjoseph I mass released this to everyone and I'm still seeing it in the logs. 

I still can't figure out exactly how it's happening though, the log lines aren't lining up with the dial plan... Is it possible those log entries could be asynchronously printed? They're also referencing a channel name that doesn't exist (the external-kamailio-000011ea bit, it doesn't actually match any real channels)

**Comment by gtjoseph** [comment] 2024-09-12 03:12
Log ERROR, WARNING NOTICE, etc. messages are processed by the logger thread but dialplan output is processed through the logger and same thread so they _should_ line up.  The stir_shaken messages can reference a channel or if no channel exists, an endpoint but the first check in the functions that had the original issue is now the global_disabled check so I'm a bit confused.  Can you attach or paste a sample?

**Comment by gtjoseph** [comment] 2024-09-12 03:40
The line numbers in the stir_shaken messages don't line up with the new code.
`res_stir_shaken/verification.c:670` is now a non-logging return when verification is disabled.  That line did _previously_ print the "Must provide caller_id" message.  Are you absolutely sure you compiled with the new code?  Exactly what did you compile?  Did you pull down the current 20 branch after it merged?  Pull the PR down and apply it over something else?

**Comment by lukeescude** [comment] 2024-09-12 03:42
I took the release of 20.8.1, downloaded the git diff patch for just your patch, then `git apply`'d it. I manually checked the code too, to make sure it lined up, but maybe I checked the wrong file somehow.

So it looks like I didn't do it right - I will dig into this more tomorrow, but I do believe your code should have fixed it, so I am betting we can close this.

**Comment by gtjoseph** [comment] 2024-09-12 03:44
We were planning to do releases candidates tomorrow but we'll hold off until later in the day in case you find something.  We can leave the ticket open for now.  Better to be safe.

**Comment by lukeescude** [comment] 2024-09-12 12:36
Alright, the patch is successfully applied to attestation but not verification - that's something on my side, probably because I'm applying it to 20.8.1 instead of the newer versions.

**Comment by gtjoseph** [comment] 2024-09-12 12:54
OK, we're going to hold off on the release candidates for a few hours anyway, just in case.

**Comment by gtjoseph** [comment] 2024-09-12 16:32
@lukeescude Have you had a chance to confirm that the issue was caused by the patch not being applied correctly?

**Closed** 2024-09-12 19:41 UTC
Labels: bug, support-level-core

**Comment by lukeescude** [comment] 2024-09-13 12:34
Yes I have, you're good to go!
